[character] 
success_symbol = "[â¯](bold #a6a6a6)"  
error_symbol   = "[â¯](bold #d75f5f)" 

[directory]
format = "[$path]($style) "
style = "bold #b0b0b0" 
truncation_length = 3
truncate_to_repo = true
truncation_symbol = ""

[git_branch]
format = "on [$symbol$branch]($style) "
symbol = "îœ¥ " 
style = "bold #808080" 

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "bold #d75f5f"

[cmd_duration]
format = "\t[$duration]($style) "
style = "bold #c0c0c0" 
min_time = 0

[package]
format = "[$symbol$version]($style) "
symbol = "ğŸ“¦ "
style = "bold #9e9e9e" 

[aws]
disabled = true

[gcloud]
disabled = true

